import type { Metadata } from "next";
// Import kiểu dữ liệu Metadata từ Next.js để định nghĩa metadata cho trang

import localFont from "next/font/local";
// Import hàm dùng để load font cục bộ (dù ở đây chưa dùng tới)

import "./globals.css";
// Import file CSS toàn cục để áp dụng style cho toàn bộ ứng dụng

export const metadata: Metadata = {
  title: "Create Next App", 
  // Tiêu đề mặc định của trang
  description: "Generated by create next app",
  // Mô tả mặc định hiển thị trong thẻ <meta name="description">
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // RootLayout là component bố cục gốc, nơi bao bọc toàn bộ ứng dụng
  // Nhận prop `children` là nội dung con sẽ được hiển thị bên trong <body>

  return (
    <html lang="en">
      {/* Thẻ html của trang, định nghĩa ngôn ngữ là tiếng Anh */}
      <body>{children}</body>
      {/* Nội dung của toàn bộ trang web sẽ được render tại đây */}
    </html>
  );
}
